### ISSUE TITLE
where should  we do the DB host name settings?

### ISSUE THREAD

**Issue by abhishek-buragadda** [mingrammer/go-todo-rest-api-example#5]
The code shows in config.go we have to configure the username, password, dbname, dialect. It is not accepting the DB host name. Why is it so?

**Comment by abhishek-buragadda** [comment]
Correct. To test with their own DB it is better to provide the DBURI with host name also. Below is the change for that . Modify config.go accordingly to add DB host 
`dbURI := fmt.Sprintf("%s:%s@tcp(%s:3306)/%s?charset=%s&parseTime=True",
		config.DB.Username,
		config.DB.Password,
		config.DB.Host,
		config.DB.Name,
		config.DB.Charset)`

**Comment by mingrammer** [comment]
I'll support soon. Or could you send me a PR for that?
